#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 19 00:46:23 2018

@author: ran
"""
import time
import sys
sys.path.append('../')
import cv2
import numpy as np
from centroid import centerpoint
from PIL import Image,ImageDraw
import os

image_path_head   = "/home/ran/Trails/MemTrack-master/results/01T/NT221/"
#image_path_head   = "/home/ran/Trails/MemTrack-master/results/02T/"
image_path_tail   = ".jpg"
image_path_extra  = "'"
gt_path_head = "/home/ran/Trails/PhC-C2DH-U373/01_GT/NBG/"
gt_path_tail = ".png"
gt_path_extra  = "'"
#save_path_head="/home/ran/Trails/MemTrack-master/results/02T/withGT/"
save_path_head="/home/ran/Trails/MemTrack-master/results/01T/NT221/withGT/"

save_path_tail = ".png"


for idx in range(1,115):
    idxname = "%03d" % idx
    idx2 = "%04d" % idx
    image_seq     = idxname
    image_path    = "%s%s%s"%(image_path_head,idx2,image_path_tail)
    gt_path = "%s%s%s"%(gt_path_head,image_seq,gt_path_tail)
    save_path="%s%s%s"%(save_path_head,image_seq,save_path_tail)
    idx1 = idx-1
    
    
    image=Image.open(image_path)
    image=image.convert("RGBA")
    gt=Image.open(gt_path)
    gt=gt.convert("RGBA")

    final = Image.new("RGBA", image.size)
    final = Image.alpha_composite(final, image)
    final = Image.alpha_composite(final, gt)
    final.save(save_path)


###################################################################


