#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 22 18:59:32 2018

@author: ran
"""

# ecoding=utf-8

for i in range(1,10):
    i=str(i)
    exec('ifn = r"result'+i+'.txt"')
    exec('ofn = r"NEWresult'+i+'.txt"')

    '''
    exec('infile'+i+' = open(ifn,"r") ')
    exec('outfile'+i+' = open(ofn,"w") ')
    '''
    infile=open(ifn,'r')
    outfile=open(ofn,'w')
    
    for eachline in infile.readlines():
            #去掉文本行里面的空格、\t、数字（其他有要去除的也可以放到' \t1234567890'里面）
            a = eachline
            #lines = filter(lambda ch: ch not in ' \t\n1234567890,', eachline) 
            b=a.replace('[','')
            c=b.replace(']','')
            #print (c)
            outfile.write(c) # 写入train_output.txt(此处是一股脑的全写进去，并没有做任何的分行处理)
#            outfile.write('\n')
    infile.close
    
    outfile.close

