#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  5 15:10:47 2019

@author: ran
"""

main
idxbreak=1
while idxcr < len(frame):
    if current is first frame:
        bbox0=zero.nparray      
    bbox0=bbox1
    in loop
        flag = jumping(bbox,bbox0)
        if flag = 1:    
            run_tracker(idxbreak)
            write bbox
        else:
            idxbreak=idx
            break
            
        
    