#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep  6 15:50:43 2019

@author: ra


#detect for every frame

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
#For every frame in sequence, detect the cell and using white bounding box. Output.

import time
import sys
sys.path.append('../')
import cv2
import numpy as np
#from centroid import centerpoint
from bboxdetct import bboxdetc
from combinedbbox import compare2bbox,detectoverlap
import Hungarian

#file_handle=open('/home/ran/Trails/RFL-master/tracking/result1.txt', mode= 'w')
#def drawframe(image, pred_boxes, frame_idx, seq_name=None):    
#    for idx in range(1, len(s_frames)):
#       line = linecache.getline(file_handle, idx)  
#        bbox = np.fromstring(line)
#        display_result(cur_frame,bbox, idx)
#        res.append(bbox.tolist())
#    file_handle.close()
 


tn=7 #target Number
#image_path_head  = "/home/ran/Trails/Fluo-N2DH-SIM+/01/img/"
image_path_head   = "/home/ran/Trails/BF-C2DL-MuSC/02/GT/"
#image_path_head   = "/home/ran/Data/exp_F0001 1-113/data/data/"
image_path_tail   = ".jpg"
image_path_extra  = "'"

for p in range(1,tn+1):
        p=str(p)
   # fn1='/home/ran/Trails/RFL-master/tracking/result1.txt'
        #exec('fn' + p +"='/home/ran/Trails/RFL-master/tracking/NEWresult_c"+ p +".txt'")###### New result here
        #exec('fn' + p +"='/home/ran/Trails/MemTrack-master/tracking/01T/NEWresult"+ p +".txt'")
        #exec('fn' + p +"='/home/ran/Trails/MemTrack-master/tracking/02T/result"+ p +".txt'")
        exec('fn' + p +"='/home/ran/Trails/PhC-C2DH-U373/ideo/01T/NEWresult"+ p +".txt'")
        
        
        exec('linenp'+p+'=np.loadtxt(fn'+p+')')

        
'''
fn1='/home/ran/Trails/RFL-master/tracking/result1.txt' #load txt file
...
linenp1=np.loadtxt(fn1)                                #read from txt file
...   
cp1=centerpoint(linenp1)                               #centerpoint of boundingbox
...
colo1=np.uint8(np.random.uniform(0,255,3))             #random 3-channel color
...
color1=tuple(map(int.colo1))                           #convert to int
...
'''
TotalDetect=[]
IOUtotal=[]
TotalTrack=[]
Assignmenttotal=[]
Bboxdetct=[]

start_time = time.time()
for idx in range(0,len(linenp1)):
    idx2 = idx+1
    idxname = "%04d" % idx2
    image_seq     = idxname
    image_path    = "%s%s%s"%(image_path_head,image_seq,image_path_tail)
    idx1 = idx
    #idx = "%04d" % idx1


 
 #   colo1=colo1.astype(np.int32)
    #color1=tuple(colo1)
    # image=cv2.imread(image_path,cv2.IMREAD_COLOR)
    #r, g, b = cv2.split(image)
    #image = cv2.merge([b, g, r])
    image=cv2.imread(image_path)

    Bboxdect=bboxdetc(image)
  

    Bboxdect=compare2bbox(Bboxdect)
    Bbox1=Bboxdect[~np.all(Bboxdect == 0, axis=1)]
    
    
    TrackRes=np.zeros((tn,4))
    for Q in range(0,tn):
        exec("CurTrack=linenp"+str(Q+1)+"[idx]")
        TrackRes[Q]=np.array(CurTrack)
    TrackRes=TrackRes.astype(float)
    Bboxdect=Bboxdect.astype(float)
    
       
    IOUMatrix=np.zeros((len(Bbox1),tn))
    for T in range(0,tn):
        for D in range(0,len(Bbox1)):
            
            IOUMatrix[D][T]=detectoverlap(Bbox1[D],TrackRes[T])
    for q in range(1,tn+1):
        exec("BBoxT = np.array([linenp"+str(q)+"[idx]])")      
        Bboxdect=np.concatenate((Bboxdect,BBoxT),axis=0) 
    Assignment, Unmatched_detection, Unmatched_tracker=Hungarian.assign_detections_to_trackers(IOUMatrix.T,TrackRes,Bboxdect)    
    #print('Before:',Bboxdect)
    
    #print('After:',Bbox)
    TotalDetect.append(Bbox1)
    TotalTrack.append(TrackRes)
    IOUtotal.append(IOUMatrix.T)
    Assignmenttotal.append(Assignment)
Addlist=[]
for i in range(0,len(IOUtotal)):
    pp=(IOUtotal[i]!=0).sum(axis=1)==0
    pp=pp.astype(int)
    AddIndex=np.nonzero(pp)
    print(np.array(AddIndex).ndim)
    print('FRAME:',i)
    print(AddIndex)
    
   
    Addlist.append(AddIndex)
    
    
    
    for trackid in range(0,len(Assignment)-1):
        bboxtra=TrackRes[Assignment[trackid][0]]
        bboxdec=Bboxdect[Assignment[trackid][1]]
        combinedbbox(bbox1,bbox2):
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
   
    '''
    #pp=(IOUtotal[9]!=0).sum(axis=0)==0
    #pp=pp.astype(int)
    #AddIndex=list(pp.flat)
    
    #for bs in range (0,len(Bboxdect)):
        
        #cv2.rectangle(image, (int(Bboxdect[bs][0]),int(Bboxdect[bs][1])), (int(Bboxdect[bs][0]+Bboxdect[bs][2]),int(Bboxdect[bs][1]+Bboxdect[bs][3])), (255,255,255), 2)
    
    for r in range (1,tn+1):
        r=str(r)
        exec('cv2.rectangle(image, tuple(pred_boxes'+r+'[0:2]), tuple(pred_boxes'+r+'[0:2] + pred_boxes'+r+'[2:4]), color'+r+', 2)')
       # exec('cv2.polylines(image, np.int32([points'+r+']), 0, color'+r+',2)   ')
    
    #
    cv2.rectangle(image, tuple(pred_boxes1[0:2]), tuple(pred_boxes1[0:2] + pred_boxes1[2:4]), (0,0,255), 2)       #draw bounding Box
    cv2.polylines(image, np.int32([points1]), 0, (0,0,255),2)                                                     #plot center point trajectory   
    cv2.rectangle(image, tuple(pred_boxes2[0:2]), tuple(pred_boxes2[0:2] + pred_boxes2[2:4]), (0, 255, 0), 2)
    cv2.polylines(image, np.int32([points2]), 0, (0,255,0),2)
    cv2.rectangle(image, tuple(pred_boxes3[0:2]), tuple(pred_boxes3[0:2] + pred_boxes3[2:4]), (255, 0, 0), 2)
    cv2.polylines(image, np.int32([points3]), 0, (255,0,0),2)
    cv2.rectangle(image, tuple(pred_boxes4[0:2]), tuple(pred_boxes4[0:2] + pred_boxes4[2:4]), (0, 255, 255), 2)
    cv2.polylines(image, np.int32([points4]), 0, (0,255,255),2)
    cv2.rectangle(image, tuple(pred_boxes5[0:2]), tuple(pred_boxes5[0:2] + pred_boxes5[2:4]), (255, 255, 0), 2)
    cv2.polylines(image, np.int32([points5]), 0, (255,255,0),2)
    cv2.rectangle(image, tuple(pred_boxes6[0:2]), tuple(pred_boxes6[0:2] + pred_boxes6[2:4]), (255, 0, 255), 2)
    cv2.polylines(image, np.int32([points6]), 0, (255,0,255),2)
    cv2.rectangle(image, tuple(pred_boxes7[0:2]), tuple(pred_boxes7[0:2] + pred_boxes7[2:4]), (0,0 ,0 ), 2)
    cv2.polylines(image, np.int32([points7]), 0, (0,0,0),2)
    cv2.rectangle(image, tuple(pred_boxes8[0:2]), tuple(pred_boxes8[0:2] + pred_boxes8[2:4]), (255,255 , 255), 2)
    cv2.polylines(image, np.int32([points8]), 0, (255,255,255),2)
    #
    cv2.putText(image, 'Frame: %d' %idx1, (20, 30), cv2.FONT_HERSHEY_DUPLEX, 0.8, (0, 255, 255))                #frame indicator
    #cv2.imshow('image',image)
    #cv2.putText(imageori, 'Frame: %d' %idx1, (20, 30), cv2.FONT_HERSHEY_DUPLEX, 0.8, (0, 255, 255))             #original image comparision
    #cv2.imshow('original',imageori)
    
    cv2.imwrite('/home/ran/Trails/MemTrack-master/results/01T/RES9.4/'+str(idx)+'.jpg', image)
    #cv2.imwrite('/home/ran/Data/exp_F0001 1-113/result/Res/'+str(idx2)+'.jpg', image)
                                 #save the images
    #cv2.waitKey(0)
    cv2.waitKey(200) 
    #cv2.destroyAllWindows()

end_time=time.time








'''












































#def readfile(filename):
#	with open(filename,'r') as f:
#		for line in f.readlines():
#			linestr = line.strip()
#			print (linestr)
#			linestrlist = linestr.split("\t")
#			print (linestrlist)
#			linelist = map(int,linestrlist)# 方法一
#			# linelist = [int(i) for i in linestrlist] # 方法二
#			print (linelist)
#  return linelist


   
    

