#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 23 13:42:20 2019

@author: ran
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb  4 15:15:50 2019

@author: ran
"""

import tensorflow as tf
import time
import sys
sys.path.append('../')
import config
from tracking.tracker import Tracker, Model
import os
import cv2
from centroid import centerpoint
import numpy as np
from jumping import jumping

def load_seq_config(seq_name,trackidx,cellidx):
    exec("src = os.path.join(config.otb_data_dir,'groundtruth_rect"+str(cellidx)+".txt')")
    #src = os.path.join(config.otb_data_dir,seq_name,'groundtruth_rect1.txt')
    gt_file = open(src)
    lines = gt_file.readlines()
    gt_rects = []
    for gt_rect in lines:
        rect = [int(v) for v in gt_rect[:-1].split(',')]
        gt_rects.append(rect)

    init_rect= gt_rects[trackidx]
    img_path = os.path.join(config.otb_data_dir,seq_name,'img')
    img_names = sorted(os.listdir(img_path))
    s_frames = [os.path.join(img_path, img_name) for img_name in img_names]

    return init_rect, s_frames

def display_result(image, pred_boxes, frame_idx, cp,seq_name=None):
    if len(image.shape) == 3:
        r, g, b = cv2.split(image)
        image = cv2.merge([b, g, r])
    pred_boxes = pred_boxes.astype(int)
    points=np.array(cp[1:frame_idx])
    cv2.rectangle(image, tuple(pred_boxes[0:2]), tuple(pred_boxes[0:2] + pred_boxes[2:4]), (0, 0, 255), 2)

    cv2.putText(image, 'Frame: %d' % frame_idx, (20, 30), cv2.FONT_HERSHEY_DUPLEX, 0.8, (0, 255, 255))
    #cv2.polylines(image, np.int32([points]), 0, (255,255,255))
    cv2.imshow('tracker', image)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        return True
    if config.is_save:
        cv2.imwrite(os.path.join(config.save_path, seq_name, '%04d.jpg' % frame_idx), image)





def run_tracker(trackidx,trackend,cellidx):
    config_proto = tf.ConfigProto()
    config_proto.gpu_options.allow_growth = True
   
    file_save=open('/home/ran/Trails/PhC-C2DH-U373/ideo/01T/RES6.25/result6.txt', mode= 'w')
    #response_save=open('/home/ran/Trails/N2DH-GOWH1/02/RESFILE/resultresponse24.txt', mode= 'w')
    fn6='/home/ran/Trails/PhC-C2DH-U373/ideo/01T/RES6.25/result6.txt'
    #fnp24='/home/ran/Trails/N2DH-GOWH1/02/RESFILE/resultresponse6.txt'
    linenp6=np.loadtxt(fn6) 
    cp= centerpoint(linenp6)
    
    '''
    file_save=open('/home/ran/Trails/MemTrack-master/tracking/02T/result15.txt', mode= 'w')
    fn15='/home/ran/Trails/MemTrack-master/tracking/02T/result15.txt'
    linenp15=np.loadtxt(fn15) 
    cp= centerpoint(linenp10)
    '''

#for line in fr.readlines():
#    lineArr=line.strip().split('\t')
#    dataMat.append([float(lineArr[0]),float(lineArr[1]),float(lineArr[2])],float(lineArr[3]))

    #linenp=np.loadtxt(fn)   
    with tf.Graph().as_default(), tf.Session(config=config_proto) as sess:
        os.chdir('../')
        model = Model(sess)
        tracker = Tracker(model)
        #######################################################
        trackidx=0
        #######################################################
        init_rect, s_frames = load_seq_config('',trackidx,cellidx)
        
        bbox = init_rect
        res = []
        res.append(bbox)
        start_time = time.time()
        tracker.initialize(s_frames[0], bbox)
        for idx in range(trackidx, trackend):
            tracker.idx = idx
            bbox, cur_frame,response= tracker.track(s_frames[idx])
            # #bboxw=np.array(bbox[0],bbox[1],bbox[2],bbox[3])
            ##print(bbox)
            
            bbox=bbox.astype(np.int)
            print(" ".join(str(i) for i in bbox)) 
            bboxoutput=" ".join(str(i) for i in bbox)
            print(bboxoutput)
            #print(response)
           
            response_map=response.reshape(272,272)
            exec("np.savetxt('/home/ran/Trails/PhC-C2DH-U373/ideo/01T/RES6.25/CellResponse01/resultresponse"+str(idx)+".txt',response_map)")
            response_show=255/np.max(response_map)*response_map
            print(np.max(response_map))
            exec("cv2.imwrite('/home/ran/Trails/PhC-C2DH-U373/ideo/01T/RES6.25/CellResponse01/resultresponse"+str(idx)+".jpg',response_show)")
            
            #response_save.write('\n')
            
            #file_save.write(np.array2string(bbox))
            file_save.write(bboxoutput) #bboxoutput-output as 12 13 13 13 str(bbox)-output as [12 13 13 13]
            file_save.write('\n')
            #bbox1=linenp
            display_result(cur_frame, bbox, idx,cp)
            res.append(bbox.tolist())
            time.sleep(0.001)
                        
        end_time = time.time()
        type = 'rect'
        fps = idx/(end_time-start_time)
        file_save.close()
        
    return res, type, fps

if __name__ == '__main__':
    cell_number = 8
    frame_number = 114
    for j from (0,frame_number):
        for i from (1,cell_number):
            run_tracker(j,j+1,i)
            
            
            
            
            
            
            
            
